/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-12-02 02:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>index2.jsp</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar wsUri = \"ws://localhost/spring_websocket_1201/websocket/echo\";\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\toutput = document.getElementById(\"output\");\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction send_message() {\r\n");
      out.write("\t\twebsocket = new WebSocket(wsUri);\r\n");
      out.write("\t\t// 처음 연결될 때 발생되는 이벤트\r\n");
      out.write("\t\twebsocket.onopen = function(evt) {\r\n");
      out.write("\t\t\tconsole.log(\"onopen: \" + evt);\r\n");
      out.write("\t\t\tonOpen(evt);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 서버로 부터 응답 받을 때\r\n");
      out.write("\t\twebsocket.onmessage = function(evt) {\r\n");
      out.write("\t\t\tconsole.log(\"onmessage: \" + evt);\r\n");
      out.write("\t\t\tonMessage(evt);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 에러...\r\n");
      out.write("\t\twebsocket.onerror = function(evt) {\r\n");
      out.write("\t\t\tonError(evt);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t}; // end function\r\n");
      out.write("\tfunction onOpen(evt) {\r\n");
      out.write("\t\twriteToScreen(\"Connected to Endpoint!\");\r\n");
      out.write("\t\tdoSend(textID.value);\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction onMessage(evt) {\r\n");
      out.write("\t\twriteToScreen(\"Message Received: \" + evt.data);\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction onError(evt) {\r\n");
      out.write("\t\twriteToScreen(\"ERROR: \" + evt.data);\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction doSend(message) {\r\n");
      out.write("\t\twriteToScreen(\"Message Sent: \" + message);\r\n");
      out.write("\t\t// 연결된 소켓으로 메세지를 전송\r\n");
      out.write("\t\twebsocket.send(message);\r\n");
      out.write("\t\t// websocket.close();\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction writeToScreen(message) {\r\n");
      out.write("\t\tvar pre = document.createElement(\"p\");\r\n");
      out.write("\t\tpre.style.wordWrap = \"break-word\";\r\n");
      out.write("\t\tpre.innerHTML = message;\r\n");
      out.write("\t\toutput.appendChild(pre);\r\n");
      out.write("\t\toutput.scrollTop = output.scrollHeight;\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 style=\"text-align: center;\">MyWebSocket!</h1>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<form action=\"\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"send\" onclick=\"send_message()\" />\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textID\" name=\"message\" value=\"\" />\r\n");
      out.write("\t\t\t<input id=\"textgg\" name=\"textgg\" value=\"dd\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"output\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
